# Generated by Django 4.2.13 on 2024-09-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_category_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="item_image",
            field=models.URLField(blank=True),
        ),
    ]
