# Generated by Django 4.2.13 on 2024-09-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_listing_item_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
