# Generated by Django 4.2.13 on 2024-09-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_category_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="tag",
            new_name="name",
        ),
    ]
