# Generated by Django 4.2.13 on 2024-09-13 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_rename_tag_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="auctioneer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
