# Generated by Django 4.2.13 on 2024-09-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_listing_auctioneer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="auction_winner",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="item_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="item_name",
            field=models.CharField(max_length=128),
        ),
    ]
