# Generated by Django 4.2.13 on 2024-09-15 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_remove_listing_comments_usercomment_current_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="watchers",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
