# Generated by Django 4.2.13 on 2024-09-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_alter_listing_watchers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercomment",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
