# Generated by Django 4.2.13 on 2024-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_alter_listing_item_image_alter_usercomment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="item_image",
            field=models.URLField(blank=True),
        ),
    ]
