# Generated by Django 4.2.13 on 2024-09-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_alter_listing_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="item_category",
            field=models.ForeignKey(
                blank=True,
                default="Others",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="auctions.category",
            ),
        ),
    ]
